// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: prime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *PrimeReq) Reset() {
	*x = PrimeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeReq) ProtoMessage() {}

func (x *PrimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeReq.ProtoReflect.Descriptor instead.
func (*PrimeReq) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeReq) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PrimeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res uint32 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *PrimeResp) Reset() {
	*x = PrimeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeResp) ProtoMessage() {}

func (x *PrimeResp) ProtoReflect() protoreflect.Message {
	mi := &file_prime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeResp.ProtoReflect.Descriptor instead.
func (*PrimeResp) Descriptor() ([]byte, []int) {
	return file_prime_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeResp) GetRes() uint32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_prime_proto protoreflect.FileDescriptor

var file_prime_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x22, 0x1d, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65,
	0x73, 0x32, 0x3c, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2c, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x42,
	0x1d, 0x5a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_proto_rawDescOnce sync.Once
	file_prime_proto_rawDescData = file_prime_proto_rawDesc
)

func file_prime_proto_rawDescGZIP() []byte {
	file_prime_proto_rawDescOnce.Do(func() {
		file_prime_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_proto_rawDescData)
	})
	return file_prime_proto_rawDescData
}

var file_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_proto_goTypes = []interface{}{
	(*PrimeReq)(nil),  // 0: prime.PrimeReq
	(*PrimeResp)(nil), // 1: prime.PrimeResp
}
var file_prime_proto_depIdxs = []int32{
	0, // 0: prime.PrimeService.prime:input_type -> prime.PrimeReq
	1, // 1: prime.PrimeService.prime:output_type -> prime.PrimeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_proto_init() }
func file_prime_proto_init() {
	if File_prime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_proto_goTypes,
		DependencyIndexes: file_prime_proto_depIdxs,
		MessageInfos:      file_prime_proto_msgTypes,
	}.Build()
	File_prime_proto = out.File
	file_prime_proto_rawDesc = nil
	file_prime_proto_goTypes = nil
	file_prime_proto_depIdxs = nil
}
